data_paths:
  GSM8K: "GSM8K/test.jsonl"
  AQUA: "AQUA/test.jsonl"
  MultiArith: "MultiArith/test.jsonl"
  ASDiv: "ASDiv/test.jsonl"
  SVAMP: "SVAMP/test.jsonl"
  p_GSM8K: "p_GSM8K/r-gsm.jsonl"
  GSM_Plus: "GSM_Plus/test.jsonl"
  GSM_IC: "GSM_IC/GSM-IC_mstep.json"
  StrategyQA: "StrategyQA/test.jsonl"
  wikimultihopQA: "wikimultihopQA/dev.json"
  commonsenseQA: "commonsenseQA/test.jsonl"
  date: "date/test.jsonl"
  spartQA: "spartQA/test.jsonl"
  sports: "sports/test.jsonl"
  reclor: "reclor/val.json"
  CLUTRR: "CLUTRR/test.jsonl"
  object_counting: "object_counting/test.json"
  navigate: "navigate/test.json"
  causal_judgement: "causal_judgement/test.json"
  logical_deduction_three_objects: "logical_deduction_three_objects/test.json"
  logical_deduction_five_objects: "logical_deduction_five_objects/test.json"
  logical_deduction_seven_objects: "logical_deduction_seven_objects/test.json"
  reasoning_about_colored_objects: "reasoning_about_colored_objects/test.json"
  last_letter_2: "last_letter/test_2_letter.json"
  last_letter_4: "last_letter/test_4_letter.json"
  coin: "coin/test.json"
  word_sorting: "word_sorting/test.json"
  tracking_shuffled_objects_seven_objects: "tracking_shuffled_objects_seven_objects/test.json"
  tracking_shuffled_objects_five_objects: "tracking_shuffled_objects_five_objects/test.json"
  tracking_shuffled_objects_three_objects: "tracking_shuffled_objects_three_objects/test.json"
  gpqa: "gpqa/test.json"
  GSM8K_Hard: "GSM8K_Hard/test.jsonl"
  temporal_sequences: "temporal_sequences/test.json"
  web_of_lies: "web_of_lies/test.json"
  drop_break: "drop_break/test.jsonl"
  drop_cencus: "drop_cencus/test.jsonl"
  squad: "squad/test.json" # "squad/squadv2.json" # "squad/test.json"
  medQA: "medQA/test.jsonl"
  GSM_Symbolic: "GSM_Symbolic/test.jsonl"
  LIMO: "LIMO/test.jsonl"
  bbeh_causal_judgement: "bbeh_causal_judgement/test.json"
  bbeh_boardgame: "bbeh_boardgame/test.json"
  bbeh_object_attribute: "bbeh_object_attribute/test.json"
  bbeh_spatial_reasoning: "bbeh_spatial_reasoning/test.json"
  bbeh_time_arithmetic: "bbeh_time_arithmetic/test.json"
  bbeh_disambiguation: "bbeh_disambiguation/test.json"
  bbeh_shuffle_objects: "bbeh_shuffle_objects/test.json"
  rag4rag: "rag4rag/test.json"
  IFBench: "IFBench/test.jsonl"

prompts:
  cot:
    GSM8K: "GSM8K/fewshot_cot.txt"
    AQUA: "AQUA/fewshot_cot.txt"
    MultiArith: "MultiArith/fewshot_cot.txt"
    ASDiv: "ASDiv/fewshot_cot.txt"
    SVAMP: "SVAMP/fewshot_cot.txt"
    p_GSM8K: "GSM8K/fewshot_cot.txt"
    GSM_Plus: "GSM8K/fewshot_cot.txt"
    GSM_IC: "GSM8K/fewshot_cot.txt"
    StrategyQA: "StrategyQA/fewshot_cot.txt"
    wikimultihopQA: "wikimultihopQA/fewshot_cot.txt"
    commonsenseQA: "commonsenseQA/fewshot_cot.txt"
    date: "date/fewshot_cot.txt"
    spartQA: "spartQA/fewshot_cot.txt"
    sports: "sports/fewshot_cot.txt"
    reclor: "reclor/fewshot_cot.txt"
    CLUTRR: "CLUTRR/fewshot_cot.txt"
    object_counting: "object_counting/fewshot_cot.txt"
    navigate: "navigate/fewshot_cot.txt"
    causal_judgement: "causal_judgement/fewshot_cot.txt"
    logical_deduction_three_objects: "logical_deduction_seven_objects/fewshot_cot.txt"
    logical_deduction_five_objects: "logical_deduction_seven_objects/fewshot_cot.txt"
    logical_deduction_seven_objects: "logical_deduction_seven_objects/fewshot_cot.txt"
    reasoning_about_colored_objects: "reasoning_about_colored_objects/fewshot_cot.txt"
    last_letter_2: "last_letter/fewshot_cot.txt"
    last_letter_4: "last_letter/fewshot_cot.txt"
    coin: "coin/fewshot_cot.txt"
    word_sorting: "word_sorting/fewshot_cot.txt"
    tracking_shuffled_objects_seven_objects: "tracking_shuffled_objects_seven_objects/fewshot_cot.txt"
    tracking_shuffled_objects_five_objects: "tracking_shuffled_objects_seven_objects/fewshot_cot.txt"
    tracking_shuffled_objects_three_objects: "tracking_shuffled_objects_seven_objects/fewshot_cot.txt"
    gpqa: "gpqa/fewshot_cot.txt"
    GSM8K_Hard: "GSM8K_Hard/fewshot_cot.txt"
    temporal_sequences: "temporal_sequences/fewshot_cot.txt"
    web_of_lies: "web_of_lies/fewshot_cot.txt"
    drop_break: "drop_break/fewshot_cot.txt"
    drop_cencus: "drop_cencus/fewshot_cot.txt"
    squad: "squad/fewshot_cot.txt"
    medQA: "squad/fewshot_cot.txt"
    GSM_Symbolic: "GSM8K/fewshot_cot.txt"
    bbeh_causal_judgement: "bbeh_causal_judgement/fewshot_cot.txt"
    gpqa: "gpqa/fewshot_cot.txt"
    bbeh_boardgame: "bbeh_boardgame/fewshot_cot.txt"
    bbeh_object_attribute: "bbeh_object_attribute/fewshot_cot.txt"
    bbeh_spatial_reasoning: "bbeh_spatial_reasoning/fewshot_cot.txt"
    bbeh_time_arithmetic: "date/fewshot_cot.txt"
    bbeh_disambiguation: "bbeh_disambiguation/fewshot_cot.txt"
    bbeh_shuffle_objects: "bbeh_shuffle_objects/fewshot_cot.txt"
    rag4rag: "rag4rag/fewshot_cot.txt"
    IFBench: "IFBench/fewshot_cot.txt"
  
  hot:
    GSM8K: "GSM8K/fewshot_hot.txt"
    AQUA: "AQUA/fewshot_hot.txt"
    MultiArith: "MultiArith/fewshot_hot.txt"
    ASDiv: "ASDiv/fewshot_hot.txt"
    SVAMP: "SVAMP/fewshot_hot.txt"
    p_GSM8K: "GSM8K/fewshot_sot.txt"
    GSM_Plus: "GSM8K/fewshot_hot.txt"
    GSM_IC: "GSM8K/fewshot_hot.txt"
    StrategyQA: "StrategyQA/fewshot_hot.txt"
    wikimultihopQA: "wikimultihopQA/fewshot_hot.txt"
    commonsenseQA: "commonsenseQA/fewshot_hot.txt"
    date: "date/fewshot_hot.txt"
    spartQA: "spartQA/fewshot_hot.txt"
    sports: "sports/fewshot_hot.txt"
    reclor: "reclor/fewshot_hot.txt"
    CLUTRR: "CLUTRR/fewshot_hot.txt"
    object_counting: "object_counting/fewshot_sot.txt"
    navigate: "navigate/fewshot_hot.txt"
    causal_judgement: "causal_judgement/fewshot_hot.txt"
    logical_deduction_three_objects: "logical_deduction_seven_objects/fewshot_hot.txt"
    logical_deduction_five_objects: "logical_deduction_seven_objects/fewshot_hot.txt"
    logical_deduction_seven_objects: "logical_deduction_seven_objects/fewshot_hot.txt"
    reasoning_about_colored_objects: "reasoning_about_colored_objects/fewshot_hot.txt"
    last_letter_2: "last_letter/fewshot_hot.txt"
    last_letter_4: "last_letter/fewshot_hot.txt"
    coin: "coin/fewshot_hot.txt"
    word_sorting: "word_sorting/fewshot_hot.txt"
    tracking_shuffled_objects_seven_objects: "tracking_shuffled_objects_seven_objects/fewshot_sot.txt"
    tracking_shuffled_objects_five_objects: "tracking_shuffled_objects_seven_objects/fewshot_hot.txt"
    tracking_shuffled_objects_three_objects: "tracking_shuffled_objects_seven_objects/fewshot_hot.txt"
    gpqa: "gpqa/fewshot_hot.txt"
    GSM8K_Hard: "GSM8K_Hard/fewshot_hot.txt"
    temporal_sequences: "temporal_sequences/fewshot_hot.txt"
    web_of_lies: "web_of_lies/fewshot_hot.txt"
    drop_break: "drop_break/fewshot_hot.txt"
    drop_cencus: "drop_cencus/fewshot_hot.txt"
    squad: "squad/fewshot_hot.txt"
    medQA: "medQA/fewshot_hot.txt"
    GSM_Symbolic: "GSM8K/fewshot_hot.txt"
    LIMO: "GSM8K/fewshot_hot.txt"
    bbeh_causal_judgement: "bbeh_causal_judgement/fewshot_hot.txt"
    gpqa: "gpqa/fewshot_hot.txt"
    bbeh_boardgame: "bbeh_boardgame/fewshot_hot.txt"
    bbeh_object_attribute: "bbeh_object_attribute/fewshot_hot.txt"
    bbeh_spatial_reasoning: "bbeh_spatial_reasoning/fewshot_hot.txt"
    bbeh_time_arithmetic: "bbeh_time_arithmetic/fewshot_hot.txt"
    bbeh_disambiguation: "bbeh_disambiguation/fewshot_hot.txt"
    bbeh_shuffle_objects: "bbeh_shuffle_objects/fewshot_hot.txt"
    rag4rag: "rag4rag/fewshot_hot.txt"
    IFBench: "IFBench/fewshot_hot.txt"